config/routes.rb
WetongjiWeb::Application.routes.draw do
  resources :reports

  resources :stories

  resources :advertisements

  resources :api_logs

  post "school_news/approve"
  post "school_news/top"
  resources :school_news

  post "for_staffs/approve"
  post "for_staffs/top"
  resources :for_staffs

  post "arounds/approve"
  post "arounds/top"
  resources :arounds

  post "club_news/approve"
  post "club_news/top"
  resources :club_news

  resources :people

  resources :versions

  post "information/approve"
  post "information/top"
  resources :information

  post "sensitives/batch_save"
  resources :sensitives

  get "organizer_registers/form_received"
  resources :organizer_registers

  post "exams/import"
  get "exams/upload"
  resources :exams

  mount Ckeditor::Engine => '/ckeditor'

  post "sele_courses/import"
  get "sele_courses/upload"
  resources :sele_courses

  post "courses/import"
  get "courses/upload"
  resources :courses

  resources :upload_files

  post "news/approve"
  resources :news

  resources :events

  resources :organizers

  post "admins/approve"
  post "admins/lock"
  post "admins/unlock"
  get "admins/form_received"
  devise_for :admins, :controllers => { :registrations => "registrations" } do
    get "/admins/sign_out" => "devise/sessions#destroy", :as => :destroy_admin_session
  end
  resources :admins

  post "activities/approve"
  post "activities/top"
  resources :activities

  resources :channels

  get "home/index"
  match "dashboard" => "home#index", :as => :admin_root

  resources :time_tables

  resources :teachers

  get "users/confirmation"
  get "users/welcome"
  get "users/reset_password_from_mail"
  post "users/reset_password"
  get "users/reset_password_success"
  get "users/reconfirm"
  get "users/send_reset_password_mail"
  get "users/reconfirm_all"
  post "users/batch_save"
  resources :users

  post "students/import"
  get "students/upload"
  resources :students

  get 'api/test'
  get 'api/call'
  post 'api/call'

end

app/views/admins/_agreement.html.erb
<div class="box">
	<div class="title">
		<h5>同济大学学生校园信息服务小组信源管理说明</h5>
	</div>
	<h2>同济大学学生校园信息服务小组信源管理说明</h2>
	<p class="start">
	2012年8月1⽇发布
	</p>
	<h3>第一章 总则</h3>
	<ol class="decimal">
		<li>《同济大学学生校园信息服务小组信源管理说明》（以下简称：信源管理说明）依据《同济大学学生校园信息服务小组执行规范》制定，是《同济大学学生校园信息服务小组执行规范》在信源管理方面的补充和说明性文件。</li>
		<li>《信源管理说明》为了规范同济大学学生校园信息服务小组（以下简称：信息服务小组）在信源管理中的信源招募、后台管理系统使用和信息安全及责任三方面内容而编制，是信息服务小组日常信源管理工作的指导性文件。</li>
	</ol>
	<h3>第⼆章 信源招募</h3>
	<h5>产品说明</h5>
	<ol class="decimal">
		<li>微同济校园信息移动终端为同济大学学生校园信息服务小组产品，旨在为同济大学校园各大信源提供发布和管理信息的平台，让广大师生方便快捷地获取校园活动信息，管理校园生活。</li>
	</ol>
	<h5>信源认证</h5>
	<ol class="decimal">
		<li>微同济后台管理系统面向同济大学校园各大信源开放和给予认证。开放信源分为官方和非官方。其中官方信源为：同济大学各职能部门、同济大学各学院团学联、同济大学校友会、共青团同济大学委员会各部门、同济大学学生会、同济大学研究生会、同济大学社团联合会。非官方信源定义为各学生社团、自发性校内组织和校外组织，需通过同济大学学生校园信息服务小组审核后方可申请成为信源。</li>
		<li>各信源在完成认证后需明确委派一名负责人在同济大学学生校园信息服务小组的协助和管理下完成社区帐号开通和信息管理的工作。</li>
	</ol>
	<h5>帐号管理</h5>
	<ol class="decimal">
		<li>各信源负责人可申请微同济后台管理系统帐号，该帐号为信源公共邮箱。信源负责人在开通账号后可以修改账号密码，并主意妥善保管。</li>
		<li>该帐号信源用户拥有查看/发布/编辑/删除活动信息以及修改账户头像的权限。</li>
		<li>信源负责人更换或信源解散时，必须以书面形式告知同济大学学生校园信息服务小组，并更改信源负责人信息或帐号注销。</li>
	</ol>
	<h5>申请流程</h5>
	<ol class="decimal">
		<li>信源申请流程包括双方沟通并达成合作意愿、填写申请表并递交、后台创建帐号并移交、档案管理与备份四个阶段。</li>
		<li>申请信源需提前准备好相关的资料如信源全名、公共邮箱和信源头像, 头像为250*250的方形大小。</li>
		<li>申请信源需准确如实填写《微同济信源账号申请表》，完成后递交至同济大学学生校园信息服务小组运营与推广部审核。</li>
		<li>审核通过后运营与推广部通过后台管理系统为申请信源开通账号，并将账号信息录入《微同济后台账户统计表》，同时通过邮件形式通知申请信源。</li>
	</ol>
	<h3>第三章 使用</h3>
	<ol class="decimal">
		<li>所有活动信息指在某一天内某个时段举办的单次活动，由信源参照《微同济后台管理系统使用指导》直接在微同济后台管理系统上进行发布，相关活动信息将在“微同济-活动”功能中进行展现。</li>
		<li>发布活动时请需注意活动开始时间最早为7：00，结束时间最晚为22：00。</li>
		<li>活动名称原则上没有字长限制，但建议控制在20个字符之内，对于讲座信息，建议把主讲人信息放在活动描述中填写。</li>
		<li>活动地点字长不能超过30个字符。</li>
		<li>对于过长的描述信息，可适当做删减和排版，建议首行不缩进。</li>
		<li>每次活动可以配图一张，图片须为jpg,png,bmp格式，文件大小不超过1M，文件名不包含中文字符。</li>
		<li>发布活动时需如实选择活动类型，目前支持“学术讲座”“校园赛事”“文娱活动”“企业招聘”四类，若在发布活动信息时队分类存在疑虑请及时联系对应的信息管理专员。</li>
		<li>建议活动发布时间至少比活动开始时间提前24小时。</li>
	</ol>
	<h3>第四章 信息安全及责任</h3>
	<h5>信息安全</h5>
	<ol class="decimal">
		<li>信源所发布信息不得违反国家法律、社会公德，同济大学学生校园信息服务小组有权对违反上述承诺的内容予以删除。</li>
		<li>信源所发布信息必须符合实际情况，不得弄虚作假，如遇信息不符的情况，一切责任由该社区负责人承担。</li>
		<li>信源所发布信息不得侵犯他人知识产权、隐私权和版权。</li>
	</ol>
	<h5>免责声明</h5>
	<ol class="decimal">
		<li>组织所发布信息不代表同济大学学生校园信息服务小组的立场和观点。作为内容的发表方，需自行对所发表内容负责，因所发表内容引发的一切纠纷，由该内容的发表方承担全部法律及连带责任。</li>
		<li>微同济后台管理系统不保证网络服务一定能满足用户的要求，也不保证网络服务不会中断。同济大学学生校园信息服务小组对因网络通信或硬件故障引起的服务中断拥有最终解释权。</li>
		<li>本声明解释权归同济大学学生校园信息服务小组所有。</li>
	</ol>
	<h3>第五章 附则</h3>
	<ol class="decimal">
		<li>《信源管理说明》解释权归管理委员会所有。</li>
		<li>《信源管理说明》经由管理委员会会议讨论通过并由执行总监和运营总监签字后生效。</li>
		<li>《信源管理说明》的修订时间间隔不能小于1年，由运营与推广部信息管理单元提议修订，经管理委员会审批通过。</li>
	</ol>
</div>

app/views/admins/_form.html.erb
<%= form_for(@admin, :html => {:multipart => true, :class => 'form-horizontal'}) do |f| %>

  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">邮箱</label>
            <div class="controls">
              <%= f.text_field :email, { :class => "m-wrap span12" } %>
            </div>
        </div>
    </div>
  </div>

  <% if can?(:manage, Admin) %>
  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">角色</label>
            <div class="controls">
              <%= f.select :role, { "普通管理员" => "CommonAdmin", "超级管理员" => "SuperAdmin" } %>
            </div>
        </div>
    </div>
  </div>
  <% end %>

  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
              <%= f.password_field :password, { :class => "m-wrap span12" } %>
            </div>
        </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">确认密码</label>
            <div class="controls">
              <%= f.password_field :password_confirmation, { :class => "m-wrap span12" } %>
            </div>
        </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">社团名称</label>
            <div class="controls">
              <%= f.text_field :display, { :class => "m-wrap span12" } %>
            </div>
        </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">图标(jpeg,正方形,文件名不能有中文,300K以内)</label>
            <div class="controls">
              <%= f.file_field :icon, { :size => "40" } %>
            </div>
        </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">背景(jpeg,正方形,文件名不能有中文,300K以内)</label>
            <div class="controls">
              <%= f.file_field :background, { :size => "40" } %>
            </div>
        </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">简介(200个汉字以内)</label>
            <div class="controls">
              <%= f.text_area :description, { :class => "m-wrap span12", :rows => 8, :cols => 80 } %>
            </div>
        </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">简介(200个汉字以内)</label>
            <div class="controls">
              <%= f.text_area :description, { :class => "m-wrap span12", :rows => 8, :cols => 80 } %>
            </div>
        </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">姓名</label>
            <div class="controls">
              <%= f.text_field :name, { :class => "m-wrap span12" } %>
            </div>
        </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">学号</label>
            <div class="controls">
              <%= f.text_field :student_no, { :class => "m-wrap span12" } %>
            </div>
        </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">职位</label>
            <div class="controls">
              <%= f.text_field :title, { :class => "m-wrap span12" } %>
            </div>
        </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">电话</label>
            <div class="controls">
              <%= f.text_field :phone, { :class => "m-wrap span12" } %>
            </div>
        </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">住址</label>
            <div class="controls">
              <%= f.text_field :address, { :class => "m-wrap span12" } %>
            </div>
        </div>
    </div>
  </div>

  <% if can? :manage, Admin %>
  <div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label class="control-label">权限</label>
            <div class="controls">
              <input type="checkbox" name="permissions[]" value="SchoolNews" <%= @admin.has_permission("SchoolNews") ? "checked" : "" %> />管理校园新闻
              <input type="checkbox" name="permissions[]" value="ClubNews" <%= @admin.has_permission("ClubNews") ? "checked" : "" %> />管理团队通告
              <input type="checkbox" name="permissions[]" value="ForStaff" <%= @admin.has_permission("ForStaff") ? "checked" : "" %> />管理校务信息
              <input type="checkbox" name="permissions[]" value="Around" <%= @admin.has_permission("Around") ? "checked" : "" %> />管理周边推荐
              <input type="checkbox" name="permissions[]" value="Person" <%= @admin.has_permission("Person") ? "checked" : "" %> />管理每周人物
            </div>
        </div>
    </div>
  </div>
  <% end %>
      
  <div class="form-actions">
      <button type="submit" class="btn light-grey"><i class="icon-ok"></i> 保存</button>
  </div>
<% end %>

app/views/admins/edit.html.erb
<% @title = "管理员" %>
<% @description = "系统管理员" %>
<% @controller = "管理员" %>
<% @action = "修改管理员" %>


<div class="portlet box light-grey">
    <div class="portlet-title">
        <div class="caption"><i class="icon-reorder"></i>修改管理员</div>
    </div>
    <div class="portlet-body form">
	<%= render 'form' %>
	</div>
</div>

app/views/admins/form_received.html.erb
<div id="content">
	<div class="box">
		<div class="title">
			<h5>您的申请已经收到</h5>
		</div>
		<h2>您的申请已经收到</h2>
		<p class="start">您的申请已经收到，请耐心等待管理员对您的申请做出审核，我们会在3个工作日内告知您审核的结果，请留意查收邮件。
		</p>
		<div class="form">
			<form action="/" method="get">
			<div class="fields">
				<div class="buttons">
					<div class="highlight">
						<input type="submit" value="知道了" />
					</div>
				</div>
			</div>
			</form>
		</div>
	</div>
</div>

app/views/admins/index.html.erb
<% @title = "管理员" %>
<% @description = "系统管理员" %>
<% @controller = "管理员" %>
<% @action = "列表" %>

<div class="portlet box light-grey">
    <div class="portlet-title">
        <div class="caption"><i class="icon-group"></i>所有管理账号</div>
    </div>
    <div class="portlet-body">
        <table class="table table-hover">
            <thead>
                <tr>
                  <th>Email</th>
                  <th>姓名</th>
                  <th>学号</th>
                  <th>角色</th>
                  <th>显示名</th>
                  <th>登陆</th>
                  <th>新闻/活动/咨询</th>
                  <th>状态</th>
                  <th></th>
                </tr>
            </thead>
            <tbody>
              <% @admins.each do |admin| %>
              <tr>
                  <td><%= admin.email %></td>
                  <td><%= admin.name %></td>
                  <td><%= admin.student_no %></td>
                  <td><%= role_name(admin.role) %></td>
                  <td><%= admin.display %></td>
                  <td><%= admin.sign_in_count %></td>
                  <td><%= admin.news.size %>/<%= admin.activities.size %>/<%= admin.information.size %></td>
                  <td>
                    <% unless admin.locked_at.nil? %>
                        <span class="label label-info">已锁定</span>
                    <% else %>
                        <span class="label label-success">正常</span>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to '详情', admin %>
                    <%= link_to '编辑', edit_admin_path(admin) %>
                    <% if admin.approved_at.nil? %>
                    <%= link_to '审批', admins_approve_path(:id => admin.id), confirm: '确认审批?', method: :post %>
                    <% else %>
                    <% if admin.locked_at.nil? %>
                    <%= link_to '禁用', admins_lock_path(:id => admin.id), confirm: '确认禁用?', method: :post %>
                    <% else %>
                    <%= link_to '启用', admins_unlock_path(:id => admin.id), confirm: '确认启用?', method: :post %>
                    <% end %>
                    <% end %>
                    <% if admin.can_destroy %>
                    <%= link_to '删除', admin, confirm: '确认删除?', method: :delete %>
                    <% end %>
                  </td>
              </tr>
              <% end %>
            </tbody>
        </table>
        <%= paginate @admins %>
    </div>
    
</div>

app/views/admins/new.html.erb
<div class="box">
    <div class="title">
        <h5>创建管理员</h5>
    </div>
    <div class="table">
	<%= form_for(@admin) do |f| %>
	<div class="form">
	    <div class="fields">
	      <div class="field field-first">
	        <div class="label">
	          <label>邮箱</label>
	        </div>
	        <div class="input">
	        	<%= f.text_field :email, :class => "small" %>
	        </div>
	      </div>
	      <div class="field">
	        <div class="label">
	          <label>密码</label>
	        </div>
	        <div class="input">
	        	<%= f.password_field :password, :class => "small" %>
	        </div>
	      </div>
	      <div class="field">
	        <div class="label">
	          <label>确认</label>
	        </div>
	        <div class="input">
	        	<%= f.password_field :password_confirmation, :class => "small" %>
	        </div>
	      </div>

	      <div class="buttons">
	        <input type="submit" name="submit" value="保存" />
	      </div>
	    </div>
  	</div>
	<% end %>

    </div>
</div>

app/views/admins/select_role.html.erb
<div class="box">
    <div class="title">
        <h5>选择角色</h5>
    </div>
    <div class="table">
    	<%= form_tag '/admins/new', :method => "get" do %>
		<div class="form">
			<div class="fields">
			  <div class="field field-first">
			    <div class="label">
			      <label>角色</label>
			    </div>
				<div class="radios">
					<% roles.each do |item| %>
        			<input type="radio" name="role" value="<%= item[0] %>" />
        			<label><%= item[1] %></label>
					<% end %>
				</div>
			  </div>
			  <div class="buttons">
			    <input type="submit" value="选择角色" />
			  </div>
			</div>
  		</div>
		<% end %>
    </div>
</div>

app/views/admins/show.html.erb
<% @title = "管理员" %>
<% @description = "系统管理员" %>
<% @controller = "管理员" %>
<% @action = "详情" %>

<div class="portlet box light-grey">
    <div class="portlet-title">
        <div class="caption"><i class="icon-reorder"></i>管理员</div>
    </div>
    <div class="portlet-body form">

      <div class="form-horizontal form-view">

        <div class="row-fluid">
            <div class="span6">
              <%= render 'shared/column_show', :name => "邮箱", :content => @admin.email %>
            </div>
            <div class="span6">
              <%= render 'shared/column_show', :name => "角色", :content => role_name(@admin.role) %>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
              <%= render 'shared/column_show', :name => "创建时间", :content => @admin.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
            </div>
            <div class="span6">
              <%= render 'shared/column_show', :name => "确认时间", :content => @admin.confirmed_at.nil? ? "" : @admin.confirmed_at.strftime("%Y/%m/%d %H:%M:%S") %>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
              <%= render 'shared/column_show', :name => "审批时间", :content => @admin.approved_at.nil? ? "" : @admin.approved_at.strftime("%Y/%m/%d %H:%M:%S") %>
            </div>
            <div class="span6">
              <%= render 'shared/column_show', :name => "登陆次数", :content => @admin.sign_in_count %>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span12">
              <%= render 'shared/column_show', :name => "名称", :content => @admin.display %>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span12">
              <%= render 'shared/column_show', :name => "简介", :content => @admin.description %>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
              <%= render 'shared/column_show', :name => "姓名", :content => @admin.name %>
            </div>
            <div class="span6">
              <%= render 'shared/column_show', :name => "学号", :content => @admin.student_no %>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
              <%= render 'shared/column_show', :name => "职位", :content => @admin.title %>
            </div>
            <div class="span6">
              <%= render 'shared/column_show', :name => "手机", :content => @admin.phone %>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span12">
              <%= render 'shared/column_show', :name => "地址", :content => @admin.address %>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span12">
              <%= render 'shared/column_show', :name => "图标", :content => image_tag(@admin.icon.url(:medium)) %>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span12">
              <%= render 'shared/column_show', :name => "背景", :content => image_tag(@admin.background.url(:medium)) %>
            </div>
        </div>

        <div class="form-actions">
          <%= link_to "更新资料", edit_admin_path(@admin), { :class => "btn light-grey"} %>        </div>
      </div>
    </div>
</div>