config/routes.rb
WetongjiWeb::Application.routes.draw do
  resources :reports

  resources :stories

  resources :advertisements

  resources :api_logs

  post "school_news/approve"
  post "school_news/top"
  resources :school_news

  post "for_staffs/approve"
  post "for_staffs/top"
  resources :for_staffs

  post "arounds/approve"
  post "arounds/top"
  resources :arounds

  post "club_news/approve"
  post "club_news/top"
  resources :club_news

  resources :people

  resources :versions

  post "information/approve"
  post "information/top"
  resources :information

  post "sensitives/batch_save"
  resources :sensitives

  get "organizer_registers/form_received"
  resources :organizer_registers

  post "exams/import"
  get "exams/upload"
  resources :exams

  mount Ckeditor::Engine => '/ckeditor'

  post "sele_courses/import"
  get "sele_courses/upload"
  resources :sele_courses

  post "courses/import"
  get "courses/upload"
  resources :courses

  resources :upload_files

  post "news/approve"
  resources :news

  resources :events

  resources :organizers

  post "admins/approve"
  post "admins/lock"
  post "admins/unlock"
  get "admins/form_received"
  devise_for :admins, :controllers => { :registrations => "registrations" } do
    get "/admins/sign_out" => "devise/sessions#destroy", :as => :destroy_admin_session
  end
  resources :admins

  post "activities/approve"
  post "activities/top"
  resources :activities

  resources :channels

  get "home/index"
  match "dashboard" => "home#index", :as => :admin_root

  resources :time_tables

  resources :teachers

  get "users/confirmation"
  get "users/welcome"
  get "users/reset_password_from_mail"
  post "users/reset_password"
  get "users/reset_password_success"
  get "users/reconfirm"
  get "users/send_reset_password_mail"
  get "users/reconfirm_all"
  post "users/batch_save"
  resources :users

  post "students/import"
  get "students/upload"
  resources :students

  get 'api/test'
  get 'api/call'
  post 'api/call'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	#load_and_authorize_resource
	before_filter :authenticate_admin!
  def index
  end
end

app/helpers/api/home_helper.rb
# encoding: utf-8
module Api
	module HomeHelper
		def home
			# banners
			user = get_current_user

			ads = Advertisement.order("id desc").limit(2)
			ex_ads = []
			ads.each do |n|
				ex_ads << ExAdvertisement.init_from_advertisement(n)
			end

			activity = Activity.where('top = 1').order("id desc").first
			ex_act = nil
			unless activity.nil?
				ex_act = ExActivity.init_from_activity(activity)
			end
				
			info = Information.where('top = 1').order('id desc').first
			ex_info = nil
			unless info.nil?
				ex_info = ExInformation.init_from_information(info)
			end

			# information
			info = Information.find_by_sql("select * from information where id in (select id from (select max(id) as id from information group by category) as tb)")
			ex_information = []
			info.each do |i|
				ex_information << ExInformation.init_from_information(i, user)
			end

			# feature
			person = Person.order('id desc').first
			ex_person = nil
			if person
				ex_person = ExPerson.init_from_person(person, user)
			end

			# activity
			activities = Activity.find_by_sql("select * from activities where id in (select id from (select max(id) as id from activities group by channel_id) as tb)")
			ex_activities = []
			activities.each do |a|
				ex_activities << ExActivity.init_from_activity(a, user)
			end

			# account
			account_new = Admin.order('id desc').where("sign_in_count > 0 and role = 'CommonAdmin'").first
			account_pop = Admin.order('information_count desc').where("sign_in_count > 0 and role = 'CommonAdmin'").first

			re = ApiReturn.new("000")
			re.add_data("BannerAdvertisements", ex_ads)
			re.add_data("BannerActivity", ex_act)
			re.add_data("BannerInformation", ex_info)
			re.add_data("Information", ex_information)
			re.add_data("Person", ex_person)
			re.add_data("Activities", ex_activities)
			re.add_data("AccountPopular", ExAccount.init_from_account(account_pop, user))
			re.add_data("AccountNewest", ExAccount.init_from_account(account_new, user))
			return_response(re)
		end
	end
end

app/views/home/_report_news.html.erb
<script type="text/javascript">
$(document).ready(function () {
    <% all = News.find_by_sql("select count(id) count, date_format(`created_at`,'%y%m%d') sdate from `news` where `created_at` between adddate(now(),-15) and now() group by sdate") %>
    var news = [
    <% all.each do |item| %>
    [<%= Time.parse(item["sdate"]).to_i * 1000 + 28800000 %>,<%= item["count"] %>],
    <% end %>
    ];
    <% active = Activity.find_by_sql("select count(id) count, date_format(`created_at`,'%y%m%d') sdate from `activities` where `created_at` between adddate(now(),-15) and now() group by sdate") %>
    var activity = [
    <% active.each do |item| %>
    [<%= Time.parse(item["sdate"]).to_i * 1000 + 28800000 %>,<%= item["count"] %>],
    <% end %>
    ];
    var plot = $.plot($("#placeholder_news"), [
		{ label: "新闻", data: news },
		{ label: "活动", data: activity }
	], {
		lines: {
			show: true
		},
		points: {
			show: true
		},
		grid: {
			backgroundColor: '#fffaff',
			hoverable: true,
			clickable: true
		},
		legend: {
			show: true
		},
        xaxis: {
            mode: "time",
            timeformat: "%0m%0d"
        },
        yaxis: {
            tickDecimals: 0
        }
	});

    function showTooltip(x, y, contents) {
        $('<div id="tooltip">' + contents + '</div>').css({
            position: 'absolute',
            display: 'none',
            top: y + -36,
            left: x + -6,
            border: '1px solid #fdd',
            padding: '4px',
            'background-color': '#fee',
            opacity: 0.80
        }).appendTo("body").fadeIn(200);
    }

    var previousPoint = null;

    $("#placeholder_news").bind("plothover", function (event, pos, item) {
        $("#x").text(pos.x.toFixed(2));
        $("#y").text(pos.y.toFixed(2));

        if (item) {
            if (previousPoint != item.datapoint) {
                previousPoint = item.datapoint;

                $("#tooltip").remove();
                var x = item.datapoint[0].toFixed(2),
                    y = item.datapoint[1].toFixed(2);

                showTooltip(item.pageX, item.pageY, Math.round(y) + " " + item.series.label);
            }
        }
        else {
            $("#tooltip").remove();
            previousPoint = null;
        }
    });
});
</script>

<div class="title">
    <h5>新闻/活动情况(近15天)</h5>
    <ul class="links">
        <li><%= link_to "新闻", news_index_path %></li>
        <li><%= link_to "活动", activities_path %></li>
    </ul>
</div>
<!-- end box / title -->
<div class="sales">
    <div class="legend">
        <h6>新闻/活动情况(近15天)-合计:新闻<%= News.all.count %>/活动<%= Activity.all.count %></h6>
    </div>
    <div id="placeholder_news" style="width:auto; height:200px;"></div>
</div>

app/views/home/_report_users.html.erb
<script type="text/javascript">
$(document).ready(function () {
    <% all = User.find_by_sql("select count(id) count, date_format(`created_at`,'%Y%m%d') sdate from `users` where `created_at` between adddate(now(),-15) and now() group by sdate") %>
    var register = [
    <% all.each do |item| %>
    [<%= Time.parse(item["sdate"]).to_i * 1000 + 28800000 %>,<%= item["count"] %>],
    <% end %>
    ];
    <% active = User.find_by_sql("select count(id) count, date_format(`confirmed_at`,'%Y%m%d') sdate from `users` where `confirmed_at` between adddate(now(),-15) and now() group by sdate") %>
    var active = [
    <% active.each do |item| %>
    [<%= Time.parse(item["sdate"]).to_i * 1000 + 28800000 %>,<%= item["count"] %>],
    <% end %>
    ];

    var plot = $.plot($("#placeholder_users"), [
		{ label: "注册", data: register },
		{ label: "激活", data: active }
	], {
		lines: {
			show: true
		},
		points: {
			show: true
		},
		grid: {
			backgroundColor: '#fffaff',
			hoverable: true,
			clickable: true
		},
		legend: {
			show: true
		},
        xaxis: {
            mode: "time",
            timeformat: "%0m%0d"
        }
	});

    function showTooltip(x, y, contents) {
        $('<div id="tooltip">' + contents + '</div>').css({
            position: 'absolute',
            display: 'none',
            top: y + -36,
            left: x + -6,
            border: '1px solid #fdd',
            padding: '4px',
            'background-color': '#fee',
            opacity: 0.80
        }).appendTo("body").fadeIn(200);
    }

    var previousPoint = null;

    $("#placeholder_users").bind("plothover", function (event, pos, item) {
        $("#x").text(pos.x.toFixed(2));
        $("#y").text(pos.y.toFixed(2));

        if (item) {
            if (previousPoint != item.datapoint) {
                previousPoint = item.datapoint;

                $("#tooltip").remove();
                var x = item.datapoint[0].toFixed(2),
                    y = item.datapoint[1].toFixed(2);

                showTooltip(item.pageX, item.pageY, Math.round(y) + " " + item.series.label);
            }
        }
        else {
            $("#tooltip").remove();
            previousPoint = null;
        }
    });
});
</script>

<div class="title">
    <h5>用户注册/激活情况(近15天)</h5>
    <ul class="links">
        <li><%= link_to "用户", users_path %></li>
    </ul>
</div>
<!-- end box / title -->
<div class="sales">
    <div class="legend">
        <h6>用户注册/激活情况(近15天)-合计:注册<%= User.all.count %>/激活<%= User.where("confirmed_at is not null").count %>/未激活<%= User.where("confirmed_at is null").count %></h6>
    </div>
    <div id="placeholder_users" style="width:auto; height:200px;"></div>
</div>

app/views/home/index.html.erb
<div class="box">
	<%= render "report_users" %>
</div>
<div class="box">
	<%= render "report_news" %>
</div>