config/routes.rb
WetongjiWeb::Application.routes.draw do
  resources :reports

  resources :stories

  resources :advertisements

  resources :api_logs

  post "school_news/approve"
  post "school_news/top"
  resources :school_news

  post "for_staffs/approve"
  post "for_staffs/top"
  resources :for_staffs

  post "arounds/approve"
  post "arounds/top"
  resources :arounds

  post "club_news/approve"
  post "club_news/top"
  resources :club_news

  resources :people

  resources :versions

  post "information/approve"
  post "information/top"
  resources :information

  post "sensitives/batch_save"
  resources :sensitives

  get "organizer_registers/form_received"
  resources :organizer_registers

  post "exams/import"
  get "exams/upload"
  resources :exams

  mount Ckeditor::Engine => '/ckeditor'

  post "sele_courses/import"
  get "sele_courses/upload"
  resources :sele_courses

  post "courses/import"
  get "courses/upload"
  resources :courses

  resources :upload_files

  post "news/approve"
  resources :news

  resources :events

  resources :organizers

  post "admins/approve"
  post "admins/lock"
  post "admins/unlock"
  get "admins/form_received"
  devise_for :admins, :controllers => { :registrations => "registrations" } do
    get "/admins/sign_out" => "devise/sessions#destroy", :as => :destroy_admin_session
  end
  resources :admins

  post "activities/approve"
  post "activities/top"
  resources :activities

  resources :channels

  get "home/index"
  match "dashboard" => "home#index", :as => :admin_root

  resources :time_tables

  resources :teachers

  get "users/confirmation"
  get "users/welcome"
  get "users/reset_password_from_mail"
  post "users/reset_password"
  get "users/reset_password_success"
  get "users/reconfirm"
  get "users/send_reset_password_mail"
  get "users/reconfirm_all"
  post "users/batch_save"
  resources :users

  post "students/import"
  get "students/upload"
  resources :students

  get 'api/test'
  get 'api/call'
  post 'api/call'

end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :out_id, :out_model_name, :reason, :user_id
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/api/reports_helper.rb
module Api
	module ReportsHelper
		def report_add
			if verify_action_params(['U', 'S', 'Id', 'Model', 'Reason'])
				user = verify_user_authentication
				if user
					report = Report.new
					report.out_id = params[:Id]
					report.out_model_name = params[:Model]
					report.reason = params[:Reason]
					report.user = user
					report.check
					report.save
					re = ApiReturn.new("000")
					return_response(re)
				end
			end
		end
	end
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :out_id %><br />
    <%= f.number_field :out_id %>
  </div>
  <div class="field">
    <%= f.label :out_model_name %><br />
    <%= f.text_field :out_model_name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :reason %><br />
    <%= f.text_field :reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <tr>
    <th>Out</th>
    <th>Out model name</th>
    <th>User</th>
    <th>Reason</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= report.out_id %></td>
    <td><%= report.out_model_name %></td>
    <td><%= report.user_id %></td>
    <td><%= report.reason %></td>
    <td><%= link_to 'Show', report %></td>
    <td><%= link_to 'Edit', edit_report_path(report) %></td>
    <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Out:</b>
  <%= @report.out_id %>
</p>

<p>
  <b>Out model name:</b>
  <%= @report.out_model_name %>
</p>

<p>
  <b>User:</b>
  <%= @report.user_id %>
</p>

<p>
  <b>Reason:</b>
  <%= @report.reason %>
</p>


<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>